apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jetstream-mini-controller.fullname" . }}
  labels:
    {{- include "jetstream-mini-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jetstream-mini-controller.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jetstream-mini-controller.selectorLabels" . | nindent 8 }}
        {{- include "jetstream-mini-controller.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: "Deployment"
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "jetstream-mini-controller.fullname" . }}
          resources:
            {{ include "jetstream-mini-controller.resources" . | nindent 12 }}
          {{- include "jetstream-mini-controller.container.image" . | nindent 10 }}
          ports:
            # Prometheus-dedicated port alias
            - containerPort: 8080
              name: metrics
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Djava.util.logging.manager=org.jboss.logmanager.LogManager
                -Dquarkus.http.host=0.0.0.0
                -XX:InitialRAMPercentage={{ .Values.resources.javaHeap.maxMemPercentage }}
                -XX:MaxRAMPercentage={{ .Values.resources.javaHeap.maxMemPercentage }}
                {{ default "" .Values.javaOptions }}
            {{- include "jetstream-mini-controller.environment.variables" . | nindent 12 }}
            - name: CONFIG_MOUNT_PATH
              value: {{ .Values.config.mountPath | quote }}
            - name: CONFIG_FILENAME
              value: {{ .Values.config.fileName | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.config.mountPath }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              port: 8080
              path: /q/health/live
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              port: 8080
              path: /q/health/ready
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "jetstream-mini-controller.fullname" . }}-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}